version: "3"

services:
  arq-maranhense:
    build: .
    container_name: arq-maranhense
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
      - ./static:/app/static
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - npm_network

networks:
  npm_network:
    external: true
